home: &home_path /home/sei/repo/topology-control # all other paths are relative to home

artifacts_config:
  save_artifacts_to: artifacts 

processor_config:
  skip_processing: false
  dataset_paths:
    raw: &raw_data_path data/raw 
    processed: &processed_data_path data/processed 

  dataset_type: &dataset_type volumesdf

  train_val_split: 0.8
  use_same_shapes_for_val: true  # Set to true for DeepSDF overfitting

  # Point cloud parameters
  point_cloud_params:
    radius: 0.02
    sigma: 0.02
    mu: 0.0
    n_gaussian: 5
    n_uniform: 1000

  # Volume processor params
  volume_processor_params:
    device: cpu  # Keep volume processing on CPU to save GPU memory
    resolution: 50

model_config:
  skip_building: false
  model_name: VolumeDeepSDF

  deepsdf:
    z_dim: 16
    layer_size: 256
    volume_hidden_dim: 128
    dropout_p: 0.2

  volumedeepsdf:
    z_dim: 2
    layer_size: 256
    volume_hidden_dim: 128
    dropout_p: 0.2

trainer_config:
  skip_training: false
  
  # Device configuration with fallback
  device: auto  # Options: 'auto', 'cuda', 'cpu', 'cuda:0', etc.
  allow_cpu_fallback: true  # Fall back to CPU if CUDA OOM
  memory_efficient: true    # Enable memory optimization techniques
  
  # Training parameters
  batch_size: 2  # Reduced from 8 to save memory
  num_epochs: 1000
  learning_rate: 0.001
  latent_learning_rate: 0.01
  
  # Memory management
  gradient_accumulation_steps: 4  # Accumulate gradients to simulate larger batch
  max_points_per_batch: 100000      # Limit points per batch to save memory
  
  # DeepSDF parameters
  dataset_type: *dataset_type
  sdf_delta: 1.0
  latent_sd: 0.01
  latent_mean: 0.0
  
  # Model saving
  save_frequency: 500
  save_best_only: false

evaluator_config:
  skip_evaluation: false        # Set to true to skip evaluation step
  batch_size: 16               # Batch size for evaluation
  resolution: 50               # Grid resolution for SDF evaluation (50³ = 125,000 points)
  max_samples: 3               # Maximum number of samples to extract meshes for
  visualization: true          # Whether to show polyscope visualizations
  save_meshes: true           # Whether to save extracted meshes as files
