home: &home_path /home/sei/repo/topology-control # all other paths are relative to home

artifacts_config:
  save_artifacts_to: artifacts 

processor_config:
  skip_processing: false
  use_train_for_val: true
  dataset_paths:
    raw: &raw_data_path data/raw 
    processed: &processed_data_path data/processed 

  train_val_split: .99

  # Updated point cloud params to match your notebook
  point_cloud_params:
    radius: 0.01
    sigma: 0.01  # Match your notebook's sigma = radius
    mu: 0.0
    n_gaussian: 20  
    n_uniform: 10000  

  # Volume processor params for SDF generation
  volume_processor_params:
    device: cpu
    resolution: 64  # Match your notebook's resolution = 50

model_config:
  skip_building: false
  model_name: lipschitz_deepsdf
  # DeepSDF specific parameters matching your notebook
  z_dim: 2  # Z_DIM = 2 from your notebook
  layer_size: 128
  coord_dim: 3  # 3D coordinates
  dropout_p: 0.1

trainer_config:
  skip_training: false
  processed_data_path: *processed_data_path
  dataset_type: lipschitz_sdf  # Important: specify SDF dataset type
  loss_function: deepsdf  # Use custom DeepSDF loss
  lipschitz_lambda: 0.00001
  optimizer: adamw
  network_learning_rate: 0.001  # lr=1e-3 from your notebook
  latent_learning_rate: 0.001
  batch_size: 2  # BATCH_SIZE = 16 from your notebook
  num_epochs: 3000  # max_epochs=20 from your notebook
  max_points: 10000  # Allow more points for better SDF learning
  
  # DeepSDF specific training parameters
  sdf_delta: 1.0  # DELTA = 1.0 from your notebook
  latent_sd: 0.01  # LATENT_SD = 0.01 from your notebook
  latent_mean: 0.0  # LATENT_MEAN = 0 from your notebook
  
  # SDF Dataset configuration - ensure dataset_info is available
  dataset_info:
    processed_data_path: *processed_data_path
    volume_coords_path: null  # Will be set by processor
    train_files: []  # Will be populated by processor
    val_files: []    # Will be populated by processor
    latent_vectors: null  # Will be initialized by trainer
  
  # Model saving
  save_model: true
  save_best_only: false
  save_frequency: 1000
  
evaluator_config:
  skip_evaluation: false
  # Evaluation specific configs for mesh extraction
  batch_size: 2
  resolution: 60  # Match training resolution for mesh extraction
  test_data_path: *processed_data_path